# Generated by Django 5.1.7 on 2025-06-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0002_ptprofile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
