# Generated by Django 5.1.7 on 2025-06-05 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0003_ptprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='ptprofile',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pt_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
